import React, { useState } from 'react'

const AmazonElecticDashboard = () => {
  const [currentCountry] = useState(localStorage.getItem("selectedCountry"))
    const url = currentCountry === 'us'
    ? `http://192.168.1.182:5601/app/discover#/?_a=(columns:!(syenappId),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'1cdb7f70-2464-11ed-900c-898c1d55d869',key:syenappId.keyword,negate:!t,params:!('kevinaarosh@syenapp.com','rama@syenapp.com','pravintest@syenapp.com','kaviya@syenapp.com','priyaprod@syenapp.com','mani@syenapp.com','vignesh@syenapp.com','deivendran@syenapp.com','devan@syenapp.com','boopathiraj@syenapp.com','sarathkumar@syenapp.com','jimmy@syenapp.com','shiva@syenapp.com','gayathri@syenapp.com','arvind@syenapp.com','testing23@syenapp.com','adrianatesting@syenapp.com','normantesting@syenapp.com','aniruddh@syenapp.com','xandertesting@syenapp.com','santhoshtest@syenapp.com','madrastesting@syenapp.com'),type:phrases,value:!('kevinaarosh@syenapp.com','rama@syenapp.com','pravintest@syenapp.com','kaviya@syenapp.com','priyaprod@syenapp.com','mani@syenapp.com','vignesh@syenapp.com','deivendran@syenapp.com','devan@syenapp.com','boopathiraj@syenapp.com','sarathkumar@syenapp.com','jimmy@syenapp.com','shiva@syenapp.com','gayathri@syenapp.com','arvind@syenapp.com','testing23@syenapp.com','adrianatesting@syenapp.com','normantesting@syenapp.com','aniruddh@syenapp.com','xandertesting@syenapp.com','santhoshtest@syenapp.com','madrastesting@syenapp.com')),query:(bool:(minimum_should_match:1,should:!((match_phrase:(syenappId.keyword:'kevinaarosh@syenapp.com')),(match_phrase:(syenappId.keyword:'rama@syenapp.com')),(match_phrase:(syenappId.keyword:'pravintest@syenapp.com')),(match_phrase:(syenappId.keyword:'kaviya@syenapp.com')),(match_phrase:(syenappId.keyword:'priyaprod@syenapp.com')),(match_phrase:(syenappId.keyword:'mani@syenapp.com')),(match_phrase:(syenappId.keyword:'vignesh@syenapp.com')),(match_phrase:(syenappId.keyword:'deivendran@syenapp.com')),(match_phrase:(syenappId.keyword:'devan@syenapp.com')),(match_phrase:(syenappId.keyword:'boopathiraj@syenapp.com')),(match_phrase:(syenappId.keyword:'sarathkumar@syenapp.com')),(match_phrase:(syenappId.keyword:'jimmy@syenapp.com')),(match_phrase:(syenappId.keyword:'shiva@syenapp.com')),(match_phrase:(syenappId.keyword:'gayathri@syenapp.com')),(match_phrase:(syenappId.keyword:'arvind@syenapp.com')),(match_phrase:(syenappId.keyword:'testing23@syenapp.com')),(match_phrase:(syenappId.keyword:'adrianatesting@syenapp.com')),(match_phrase:(syenappId.keyword:'normantesting@syenapp.com')),(match_phrase:(syenappId.keyword:'aniruddh@syenapp.com')),(match_phrase:(syenappId.keyword:'xandertesting@syenapp.com')),(match_phrase:(syenappId.keyword:'santhoshtest@syenapp.com')),(match_phrase:(syenappId.keyword:'madrastesting@syenapp.com'))))))),hideChart:!t,index:'15217f20-2d4a-11ed-bdf3-dbbb4c6e5c75',interval:auto,query:(language:kuery,query:'domain.keyword%20:%22amazon%22%20and%20c_p_name.keyword%20:%22Revision%20to%20Your%20Amazon.com%20Account%22%20'),sort:!(!(processed_date,desc)))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d%2Fd,to:now))`
    : `http://192.168.1.182:5643/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(columns:!(syenappId,merchant_name,c_p_name),filters:!(),index:a93b41b1-bd06-4f2f-b79a-31a39c23187f,interval:auto,query:(language:kuery,query:'merchant_name.keyword%20:%22Amazon%22%20and%20c_p_name.keyword%20:%22Revision%20to%20Your%20Amazon.com%20Account%22%20'),sort:!(!(cDate,desc)))`
  return (
    <div className='page-container'>
        <iframe title='amazon-signup-users-elastic-dashboard' src={url} style={{height:window.innerHeight,width:'100%',border:'none'}} ></iframe>
    </div>
  )
}

export default AmazonElecticDashboard